### ISSUE TITLE
Mount whole `/dev`

### ISSUE THREAD

**Issue by jara001** [cihlami1/f1tenth-ros2-setup#1]
When the docker starts, it tries to mount all devices using `--device`:

https://github.com/cihlami1/f1tenth-ros2-setup/blob/73ad932de3572bda9564adfd81a211bf78d291da/docker_img_linux_cfg/start_container.sh#L11-L13

However, when the devices are non-existent, this step fails. (Even when the container is already created.) When testing algorithms on the car, VESC is usually not powered.

What about mounting whole `/dev` instead?

```yaml
-v /dev:/dev \
```

**Comment by cihlami1** [comment]
I am looking into this issue and tried your approach, but then the container doesn't have the right to access these devices as needed. But I'm currently trying to fix it.
